### Create book
POST http://localhost:3000/v1/books
Content-Type: application/json

{
    "title": "Crime and Punishment",
    "authorId": 2,
    "releaseYear": 1866,
    "language": "en",
    "format": "paperback",
    "price": 30
}

### Get book with given id
GET http://localhost:3000/v1/books/1

### Update book
PATCH http://localhost:3000/v1/books/1
Content-Type: application/json

{
    "description": "great book",
    "price": 50
}

### Delete book with given id
DELETE  http://localhost:3000/v1/books/1
