### Create author
POST http://localhost:3000/v1/authors
Content-Type: application/json

{
    "firstName": "Michal",
    "lastName": "Cieslar"
}

### Get author with given id
GET http://localhost:3000/v1/authors/1

### Update author
PATCH http://localhost:3000/v1/authors/2
Content-Type: application/json

{
    "about": "great author"
}

### Delete author with given id
DELETE  http://localhost:3000/v1/authors/1
